#-----------------------------------------------------------------
# Destroy Azure AKS using Terraform - Azure IaC
#
# - Add Azure DevOps Service Connection to:
#   - Azure ARM 
# 
#-----------------------------------------------------------------

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: echo Destroy Azure AKS using Terraform - Azure IaC. 
  displayName: 'Run a multi-line script'
  
  
- task: TerraformCLI@0
  inputs:
    command: 'init'
    workingDirectory: '$(System.DefaultWorkingDirectory)/Web01.kubernetes.Azure.IAC'
    backendType: 'azurerm'
    backendServiceArm: 'AzureARMConnectionDev'
    ensureBackend: true
    backendAzureRmResourceGroupName: 'Dev01-RG'
    backendAzureRmResourceGroupLocation: 'eastus'
    backendAzureRmStorageAccountName: 'dev01straccnt01'
    backendAzureRmContainerName: 'dev01strcontainer01'
    backendAzureRmKey: 'kubernetes-dev01.tfstate'



- task: TerraformCLI@0
  inputs:
    command: 'destroy'
    workingDirectory: '$(System.DefaultWorkingDirectory)/Web01.kubernetes.Azure.IAC'
    environmentServiceName: 'AzureARMConnectionDev'
    commandOptions: '-var client_id=$(client_id) -var client_secret=$(client_secret) -var ssh_public_key=$(publickey.secureFilePath) -var tenant_id=$(tenant_id) -var subscription_id=$(subscription_id) -var access_key=$(access_key)'
    
